export enum MaTracuuKHL {
  MA_TRACUU_1 = '003',
  MA_TRACUU_2 = '010',
  MA_TRACUU_3 = '050',
  MA_TRACUU_4 = '051',
  MA_TRACUU_5 = '052',
  MA_TRACUU_6 = '053',
  MA_TRACUU_7 = '060',
  MA_TRACUU_8 = '061',
  MA_TRACUU_9 = '070',
  MA_TRACUU_10 = '110',
  MA_TRACUU_11 = '120',
  MA_TRACUU_12 = '121',
  MA_TRACUU_13 = '122',
  MA_TRACUU_14 = '123',
  MA_TRACUU_15 = '124',
  MA_TRACUU_16 = '130',
}

export enum MaKiemtraKHL {
  MA_KIEMTRA_1 = '01',
  MA_KIEMTRA_2 = '02',
  MA_KIEMTRA_3 = '03',
  MA_KIEMTRA_4 = '04',
  MA_KIEMTRA_5 = '05',
  MA_KIEMTRA_6 = '06',
  MA_KIEMTRA_7 = '07',
  MA_KIEMTRA_8 = '08',
  MA_KIEMTRA_9 = '09',
  MA_KIEMTRA_11 = '11',
}

export const DS_MA_TRACUU = {
  '000': 'Thông tin thẻ BHYT chính xác',
  '001': 'Thẻ BHYT do BHXH BQP quản lý, đề nghị kiểm tra thẻ BHYT và thông tin giấy tờ tuỳ thân',
  '002': 'Thẻ BHYT do BHXH BCA quản lý, đề nghị kiểm tra thẻ BHYT và thông tin giấy tờ tuỳ thân',
  '003': 'Thẻ BHYT cũ hết giá trị sử dụng, được cấp thẻ mới',
  '004': 'Thẻ BHYT cũ còn giá trị sử dụng, được cấp thẻ mới',
  '010': 'Thẻ BHYT hết giá trị sử dụng',
  '051': 'Mã thẻ BHYT không đúng',
  '052': 'Mã tỉnh cấp thẻ BHYT (ký tự thứ 4,5) không đúng',
  '053': 'Mã quyền lợi BHYT (ký tự thứ 3) không đúng',
  '050': 'Không có thông tin thẻ BHYT',
  '060': 'Thẻ BHYT sai họ tên',
  '061': 'Thẻ BHYT sai họ tên (đúng ký tự đầu)',
  '070': 'Thẻ BHYT sai ngày sinh',
  '100': 'Lỗi khi lấy dữ liệu sổ thẻ',
  '101': 'Lỗi server',
  '110': 'Thẻ BHYT đã thu hồi',
  '120': 'Thẻ BHYT đã báo giảm',
  '121': 'Thẻ BHYT đã báo giảm chuyển ngoại tỉnh',
  '122': 'Thẻ BHYT đã báo giảm chuyển nội tỉnh',
  '123': 'Thẻ BHYT đã báo giảm do tăng lại cùng đơn vị',
  '124': 'Thẻ BHYT đã báo giảm ngừng tham gia',
  '130': 'Trẻ em không xuất trình thẻ BHYT',
  '205': 'Lỗi sai định dạng tham số',
  '401': 'Lỗi xác thực tài khoản',
  '500': 'Lỗi máy chủ',
  '054': 'Số CCCD của cán bộ thực hiện tra cứu không tồn tại trong danh sách người sử dụng do CSKCB đăng ký',
  '055': 'Họ và tên của cán bộ thực hiện tra cứu không khớp với số CCCD',
}

export const DS_MA_KIEMTRA = {
  '00': 'Thông tin thẻ chính xác',
  '01': 'Thẻ hết giá trị sử dụng',
  '02': 'KCB khi chưa đến hạn',
  '03': 'Hết hạn thẻ khi chưa ra viện',
  '04': 'Thẻ có giá trị khi đang nằm viện',
  '05': 'Thẻ không có trong CSDL',
  '06': 'Thẻ sai họ tên',
  '07': 'Thẻ sai ngày sinh',
  '08': 'Thẻ sai giới tính',
  '09': 'Thông tin thẻ không chính xác',
  '10': 'Lỗi khi lấy dữ liệu sổ thẻ',
  '401': 'Lỗi xác thực tài khoản',
  '11': 'Thiếu dữ liệu đầu vào',
}
