export const MESSAGE_COMMON = {
    PASSWORD_NOT_MATCH: 'Mật khẩu không khớp',
    OLD_PASSWORD_NOT_MATCH: 'Mật khẩu cũ không khớp',
    NEW_PASSWORD_NOT_MATCH: 'Mật khẩu mới không khớp',
    PASSWORD_NOT_EMPTY: 'Mật khẩu không được để trống',
    PASSWORD_IS_STRING: 'Mật khẩu phải là chuỗi',
    USER_ID_NOT_EMPTY: 'Id người dùng không được để trống',
    USER_ID_IS_STRING: 'Id người dùng phải là chuỗi',
    PASSWORD_MIN_LENGTH: 'Mật khẩu chưa đủ độ dài tối thiểu',

    PATIENT_CODE_NOT_EMPTY: 'Mã bệnh nhân không được để trống',
    PATIENT_CODE_IS_STRING: 'Mã bệnh nhân phải là chuỗi',
    TREATMENT_CODE_NOT_EMPTY: 'Mã điều trị không được để trống',
    TREATMENT_CODE_IS_STRING: 'Mã điều trị phải là chuỗi',
    REQUEST_TYPE_NOT_EMPTY: 'Loại yêu cầu không được để trống',
    REQUEST_TYPE_IS_STRING: 'Loại yêu cầu phải là chuỗi',
    REQUEST_CONTENT_NOT_EMPTY: 'Nội dung yêu cầu không được để trống',
    REQUEST_CONTENT_IS_STRING: 'Nội dung yêu cầu phải là chuỗi',

    SURVEY_SCORE_NOT_EMPTY: 'Điểm đánh giá không được để trống',
    SURVEY_SCORE_IS_NUMBER: 'Điểm đánh giá phải là số',
    SURVEY_SCORE_MIN: 'Điểm đánh giá phải lớn hơn 0',
    SURVEY_SCORE_MAX: 'Điểm đánh giá phải nhỏ hơn 6',
    SURVEY_COMMENT_MAX_LENGTH: 'Nội dung đánh giá không được vượt quá 255 ký tự',
    SURVEY_COMMENT_IS_STRING: 'Nội dung đánh giá phải là chuỗi',
    SURVEY_COMMENT_NOT_EMPTY: 'Nội dung đánh giá không được để trống',
    SURVEY_SCORE_IS_INT: 'Điểm đánh giá phải là số nguyên',

    SURVEY_ALREADY_EXISTS: 'Bạn đã đánh giá hồ sơ này rồi',
    SURVEY_ALREADY_COMPLETED: 'Hồ sơ này đã được chốt rồi bạn không sửa được',
    SERVICE_REQ_CODE_NOT_EMPTY: 'Mã yêu cầu dịch vụ không được để trống',
    SURVEY_SERVICE_ALREADY_EXISTS: 'Bạn đã đánh giá dịch vụ này rồi',

    FAMILY_MEMBER_ID_NOT_EMPTY: 'Id thành viên gia đình không được để trống',
    FAMILY_MEMBER_ID_IS_STRING: 'Id thành viên gia đình phải là chuỗi',
    PULSE_NOT_EMPTY: 'Nhịp tim không được để trống',
    PULSE_IS_NUMBER: 'Nhịp tim phải là số',
    SYSTOLIC_NOT_EMPTY: 'Huyết áp tâm thu không được để trống',
    SYSTOLIC_IS_NUMBER: 'Huyết áp tâm thu phải là số',
    DIASTOLIC_NOT_EMPTY: 'Huyết áp tâm trương không được để trống',
    DIASTOLIC_IS_NUMBER: 'Huyết áp tâm trương phải là số',
    HEIGHT_CM_NOT_EMPTY: 'Chiều cao không được để trống',
    HEIGHT_CM_IS_NUMBER: 'Chiều cao phải là số',
    WEIGHT_KG_NOT_EMPTY: 'Cân nặng không được để trống',
    WEIGHT_KG_IS_NUMBER: 'Cân nặng phải là số',
    BMI_NOT_EMPTY: 'Chỉ số BMI không được để trống',
    BMI_IS_NUMBER: 'Chỉ số BMI phải là số',
    NOTE_IS_STRING: 'Ghi chú phải là chuỗi',
    METRIC_DATE_NOT_EMPTY: 'Ngày đo không được để trống',
    METRIC_DATE_IS_DATE: 'Ngày đo phải là ngày',
}